# Generated by Django 4.2.23 on 2025-07-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='Topic',
            new_name='topic',
        ),
    ]
